const syllabus = [
 {s:'Língua Portuguesa',q:10,t:[
  'Sistema, norma, fala e variedade linguística','Ortografia e sistema ortográfico vigente','Estrutura e formação de palavras; classes gramaticais','Flexão verbal: modos, vozes, tempos e aspectos','Flexão nominal; concordância verbal e nominal','Regência verbal e nominal','Sintaxe da oração e do período; termos da oração','Coordenação, subordinação e paralelismo sintático','Colocação pronominal; equivalência e transformação de estruturas','Discurso direto e indireto','Pontuação','Léxico, sinonímia, antonímia, denotação e conotação','Terminologia jurídica','Tipos e estrutura de texto; coesão e coerência','Ponto de vista, ideia central e ideias convergentes','Informações literais, pressupostas, implícitas e subentendidas'
 ]},
 {s:'Física',q:8,t:[
  'Grandezas físicas escalares e vetoriais; sistemas de unidades','Cinemática: velocidade, aceleração, MRUV e movimento relativo','Leis de Newton; peso, massa, atrito, arrasto e velocidade terminal','Trabalho, energia, potência e conservação da energia mecânica','Centro de massa, momento linear, colisão e impulso','Rotação, torque, momento de inércia e momento angular','Estática dos fluidos: pressão, massa específica, Pascal e Arquimedes','Forças hidrostáticas e medidores de pressão','Dinâmica dos fluidos: conservação da massa, quantidade de movimento e Bernoulli','Calorimetria, mudança de fase e calor latente','Primeira Lei da Termodinâmica; expansão e transferência de calor','Gases ideais e trabalho termodinâmico','Segunda Lei, máquinas térmicas, refrigeradores e ciclo de Carnot','Irreversibilidade, desordem e entropia'
 ]},
 {s:'Química',q:8,t:[
  'Matéria, energia, substâncias, misturas e separação de misturas','Atomística, modelos atômicos e números quânticos','Tabela periódica e propriedades periódicas','Ligações químicas e ligação metálica','Polaridade molecular e forças intermoleculares','Oxidação, redução e cálculo do NOX','Ácidos, bases, sais, óxidos e neutralização','Reações químicas, oxirredução e balanceamento','Massa, mol, massa molar e constante de Avogadro','Leis ponderais e leis de Gay-Lussac','Fórmulas centesimal, mínima e molecular; estequiometria','Gases: transformações, Clapeyron, misturas, difusão e efusão','Propriedades coligativas','Termoquímica: entalpia de formação e de combustão','Equilíbrio químico e princípio de Le Chatelier'
 ]},
 {s:'Raciocínio Lógico-Matemático',q:8,t:[
  'Conjuntos: representação, pertinência, inclusão e operações','Números naturais, inteiros, racionais e reais','Divisibilidade, fatores primos, MDC e MMC','Potenciação, radiciação, valor absoluto e intervalos','Unidades e conversão de medidas','Razão, proporção, regra de três e porcentagem','Juros simples e compostos','Expressões algébricas, identidades e polinômios','Equações, inequações e sistemas de 1º e 2º graus','Funções, função modular, inversa, polinomial, exponencial e logarítmica','Matrizes, determinantes até 4ª ordem e sistemas lineares','Geometria plana e relações métricas','Trigonometria, leis dos senos e dos cossenos','Geometria espacial: prismas, pirâmides, cilindros, cones e esferas','Geometria analítica: ponto, reta e circunferência','Sequências, PA e PG','Análise combinatória e Binômio de Newton','Probabilidade, probabilidade condicional e eventos independentes','Estatística, frequências, médias, mediana, moda e gráficos','Problemas de raciocínio lógico'
 ]},
 {s:'Direito Constitucional',q:6,t:[
  'Conceito e classificação das Constituições','Aplicabilidade e interpretação das normas constitucionais','Poder Constituinte','Princípios fundamentais','Direitos e garantias fundamentais; efetividade, limites e restrições','Proibição de retrocesso social','Habeas corpus, habeas data e mandado de segurança','Direito de petição e certidão; ação popular e ação civil pública','Direitos sociais e art. 6º da Constituição Federal','Nacionalidade','Federação, entes federativos e município','Repartição de competências','Organização e separação dos Poderes','Controle de constitucionalidade','Segurança pública e art. 144 da Constituição Federal','Ordem social'
 ]},
 {s:'Direito Administrativo',q:6,t:[
  'Conceito, fontes e princípios do Direito Administrativo','Centralização, descentralização, concentração e desconcentração','Administração direta e indireta','Poderes vinculado, discricionário, hierárquico e disciplinar','Poder regulamentar, poder de polícia, uso e abuso do poder','Ato administrativo: conceito, requisitos, perfeição, validade e eficácia','Atributos, classificação, espécies e exteriorização do ato','Extinção, desfazimento e sanatória; vinculação e discricionariedade','Responsabilidade civil da Administração e teoria do risco administrativo','Dano, exclusão da responsabilidade, reparação e ação regressiva'
 ]},
 {s:'Direito Ambiental',q:6,t:[
  'Princípios do Direito Ambiental','Meio ambiente na Constituição Federal','Competências ambientais e normas de cooperação','Poder de polícia ambiental','Licenciamento e estudo de impacto ambiental','Compensação ambiental e biossegurança','Infrações ambientais','Dano, responsabilidade e reparação ambiental','SISNAMA e SNUC'
 ]},
 {s:'Administração Pública',q:6,t:[
  'Organizações formais modernas e estruturas organizacionais','Natureza, finalidades e departamentalização','Gestão pública e gestão privada','Princípios básicos da Administração Pública','Gestão de resultados e avaliação de desempenho','Planejamento, direção, coordenação, comunicação, controle e avaliação','Planejamento estratégico, tático e operacional','Gestão de pessoas próprias e terceirizadas','Gestão por processos e por projetos','Gestão de contratos','Gestão da qualidade e excelência nos serviços públicos','Motivação e liderança','Tipos de decisão e processo decisório','Ética no serviço público'
 ]},
 {s:'Informática',q:6,t:[
  'Hardware e software','Sistemas operacionais','Linux Ubuntu e software livre','Google Workspace: documentos, planilhas e apresentações','Google Meet, Formulários e Drive','Google Chrome e Mozilla Firefox','Segurança da informação e autenticação de dois fatores','Internet, intranet e VPN','Redes WAN, MAN, LAN e protocolo TCP/IP','Roteador, switch, modem e cabeamento','Big Data e Business Intelligence','Computação em nuvem: ferramentas e plataformas'
 ]},
 {s:'Inglês',q:4,t:[
  'Leitura e interpretação de textos em inglês','Inferência de significado pelo contexto','Mecanismos de formação de palavras','Marcadores explícitos de coesão','Conexões de sentido entre períodos e parágrafos','Interpretação de afirmações implícitas e da argumentação do autor'
 ]},
 {s:'Legislação Específica',q:12,t:[
  'Lei Complementar nº 194/2012','Lei Complementar nº 052/2001','Lei Estadual nº 963/2014','Lei Federal nº 12.608/2012','Instrução Normativa nº 02/2016 do Ministério da Integração Nacional','Lei Federal nº 14.751/2023','Constituição do Estado de Roraima'
 ]}
];
const defaultCycle = [
 {s:'Língua Portuguesa',c:'Conhecimentos gerais',g:'Questões por incidência + correção',target:3,minutes:60,enabled:true},
 {s:'Legislação Específica',c:'Conhecimentos específicos',g:'Lei seca direcionada + questões',target:3,minutes:60,enabled:true},
 {s:'Física',c:'Conhecimentos gerais',g:'Teoria curta + questões bem corrigidas',target:2,minutes:60,enabled:true},
 {s:'Redação Discursiva',c:'CFO',g:'Produção, correção e reescrita',target:5,minutes:60,enabled:true},
 {s:'Direito Constitucional',c:'Conhecimentos gerais',g:'Manutenção por questões',target:1,minutes:60,enabled:true},
 {s:'Química',c:'Conhecimentos gerais',g:'Teoria curta + questões bem corrigidas',target:2,minutes:60,enabled:true},
 {s:'Direito Administrativo',c:'Conhecimentos gerais',g:'Manutenção por questões',target:1,minutes:60,enabled:true},
 {s:'Raciocínio Lógico-Matemático',c:'Conhecimentos gerais',g:'Procedimento + questões',target:2,minutes:60,enabled:true},
 {s:'Informática',c:'Conhecimentos gerais',g:'Questões + revisão curta',target:1,minutes:60,enabled:true},
 {s:'Direito Ambiental',c:'Conhecimentos gerais',g:'Questões + legislação',target:1,minutes:60,enabled:true},
 {s:'Administração Pública',c:'Conhecimentos gerais',g:'Questões + teoria direcionada',target:2,minutes:60,enabled:true},
 {s:'Inglês',c:'Conhecimentos gerais',g:'Interpretação + vocabulário recorrente',target:1,minutes:60,enabled:true},
 {s:'História',c:'CFSD',g:'Preparação complementar para Soldado',target:1,minutes:30,enabled:true},
 {s:'Geografia',c:'CFSD',g:'Preparação complementar para Soldado',target:1,minutes:30,enabled:true}
];
const legacyCycleSubjects=['Língua Portuguesa','Legislação Específica','Física','Redação Discursiva','Direito Constitucional','Química','Língua Portuguesa','Direito Administrativo','Raciocínio Lógico-Matemático','Redação Discursiva','Legislação Específica','Informática','Física','Direito Ambiental','Redação Discursiva','Química','Língua Portuguesa','Administração Pública','Raciocínio Lógico-Matemático','Legislação Específica','Inglês','Redação Discursiva','Administração Pública','Redação Discursiva','História'];
const subjects=defaultCycle.map(x=>x.s);
const defaults={
 current:0,selectedSubject:'Língua Portuguesa',selectedTopic:'',selectedMinutes:60,mode:'normal',logs:[],errors:[],essays:[],sims:[],syllabusDone:{},cycleConfig:structuredClone(defaultCycle),cycleProgress:{},roundNumber:1,
 settings:{examDate:'2026-09-27',soldierExamDate:'',weeklyHoursGoal:20,weeklyQuestionGoal:250,blockMinutes:60,showReviewsHome:true}
};
let state=loadState();
let timerSeconds=state.selectedMinutes*60,timerId=null,timerRunning=false,deferredPrompt=null,reviewTab='due',pendingSubject='';
function loadState(){try{const x=JSON.parse(localStorage.getItem('qgCbmState')),merged=deepMerge(structuredClone(defaults),x||{});if(merged.settings.examDate==='2026-09-20')merged.settings.examDate='2026-09-27';if(!x?.selectedSubject&&Number.isInteger(x?.current))merged.selectedSubject=legacyCycleSubjects[x.current%legacyCycleSubjects.length]||'Língua Portuguesa';merged.cycleConfig=normalizeCycleConfig(merged.cycleConfig);if(!merged.cycleConfig.some(c=>c.s===merged.selectedSubject&&c.enabled))merged.selectedSubject=merged.cycleConfig.find(c=>c.enabled)?.s||'Língua Portuguesa';merged.selectedMinutes=Number(merged.selectedMinutes)||merged.cycleConfig.find(c=>c.s===merged.selectedSubject)?.minutes||60;return merged}catch{return structuredClone(defaults)}}
function normalizeCycleConfig(config){const source=Array.isArray(config)?config:[];const byName=new Map(source.map(x=>[x.s,x]));return defaultCycle.map(d=>({...d,...(byName.get(d.s)||{})})).filter((x,i,a)=>a.findIndex(y=>y.s===x.s)===i)}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=deepMerge(a[k]||{},b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem('qgCbmState',JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function todayISO(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
function formatDate(d){if(!d)return 'Sem data';return new Date(d+'T12:00:00').toLocaleDateString('pt-BR')}
function isWithinDays(date,days){const now=new Date();now.setHours(0,0,0,0);const d=new Date(date+'T12:00:00');return d>=new Date(now.getTime()-(days-1)*86400000)&&d<=new Date(now.getTime()+86400000)}
function accuracy(q,c){return q>0?Math.round(c/q*100):null}
function scoreClass(p){return p===null?'':p<50?'bad':p<70?'mid':'good'}
function reviewInterval(p){if(p===null)return 7;if(p<50)return 2;if(p<70)return 7;if(p<80)return 15;return 30}
function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function isCfsdOnly(subject){return subject==='História'||subject==='Geografia'||subject==='História e Geografia'}
function cappedReviewDate(date,n,subject){const proposed=addDays(date,n);if(isCfsdOnly(subject)||!state.settings.examDate)return proposed;const lastDay=addDays(state.settings.examDate,-1);return proposed>lastDay?lastDay:proposed}
function daysUntil(date){if(!date)return null;const [y,m,d]=date.split('-').map(Number),now=new Date(),today=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()),target=Date.UTC(y,m-1,d);return Math.ceil((target-today)/86400000)}
function modeTarget(){return state.mode==='normal'?210:state.mode==='post'?120:60}
function modeHint(){return state.mode==='normal'?'3 blocos completos + 30 min de correção e flashcards.':state.mode==='post'?'2 blocos. Prefira revisão, questões médias e consolidação.':'1 bloco mínimo. Use versão leve se estiver exausto.'}
function render(){renderHeader();renderHome();renderCycle();renderSyllabus();renderReviews();renderEssay();renderPerformance();renderSettings()}
function renderHeader(){const diff=daysUntil(state.settings.examDate);$('#daysLeft').textContent=diff===null?'--':Math.max(0,diff);$('#examDateLabel').textContent=state.settings.examDate?new Date(state.settings.examDate+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}):'Data não definida';$$('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#dailyTarget').textContent=modeTarget();$('#dailyHint').textContent=modeHint()}
function activeConfigs(){return state.cycleConfig.filter(x=>x.enabled)}
function current(){return state.cycleConfig.find(x=>x.s===state.selectedSubject)||activeConfigs()[0]||defaultCycle[0]}
function subjectTopics(subject){const official=syllabus.find(x=>x.s===subject)?.t;if(official?.length)return official;if(subject==='Redação Discursiva')return['Redação completa','Introdução','Desenvolvimento','Conclusão','Correção','Reescrita'];return['Assunto livre / edital CFSD']}
function subjectStats(config){const logs=state.logs.filter(x=>x.subject===config.s),questions=logs.reduce((n,x)=>n+x.questions,0),correct=logs.reduce((n,x)=>n+x.correct,0),last=logs.map(x=>x.date).sort().at(-1)||'',daysGap=last?Math.max(0,daysUntil(last)*-1):99,due=getReviews().filter(x=>x.subject===config.s&&x.due<=todayISO()).length,done=Number(state.cycleProgress[config.s]||0),target=Math.max(1,Number(config.target)||1),p=accuracy(questions,correct);return{logs,questions,correct,last,daysGap,due,done,target,p}}
function recommendationScore(config){const s=subjectStats(config),deficit=Math.max(0,1-s.done/s.target),weak=s.questions>=10&&s.p<70?(70-s.p):0;return s.due*100+deficit*45+Math.min(25,s.daysGap*2)+weak-(s.done>=s.target?55:0)}
function recommendedConfig(){return [...activeConfigs()].sort((a,b)=>recommendationScore(b)-recommendationScore(a))[0]||current()}
function subjectStatus(config){const s=subjectStats(config);if(s.due)return{label:`${s.due} revisão${s.due>1?'ões':''} vencida${s.due>1?'s':''}`,cls:'status-review'};if(s.done>=s.target)return{label:'Meta da rodada feita',cls:'status-ok'};if(s.daysGap>=7)return{label:'Atrasada',cls:'status-late'};return{label:'Pouco estudada',cls:'status-low'}}
function recommendationText(config){const s=subjectStats(config);if(s.due)return`${config.s} é a recomendação: há ${s.due} revisão${s.due>1?'ões':''} vencida${s.due>1?'s':''}.`;if(s.questions>=10&&s.p<70)return`${config.s} é a recomendação: desempenho de ${s.p}% nas questões.`;if(s.done<s.target)return`${config.s} é a recomendação: ${s.done}/${s.target} blocos feitos nesta rodada.`;return`${config.s} é a matéria há mais tempo sem estudo recente.`}
function syllabusStats(){const total=syllabus.reduce((n,x)=>n+x.t.length,0),done=Object.values(state.syllabusDone||{}).filter(Boolean).length;return{total,done,p:total?Math.round(done/total*100):0}}
function topicKey(subject,topic){return subject+'|'+topic}
function renderHome(){const cur=current(),curStats=subjectStats(cur),rec=recommendedConfig();$('#currentBlockNum').textContent=`${curStats.done}/${curStats.target}`;$('#currentSubject').textContent=cur.s;$('#currentCore').textContent=cur.c;$('#currentGoal').textContent=state.selectedTopic||cur.g;$('#studySubject').value=cur.s;$('#homeSyllabusProgress').textContent=syllabusStats().p+'%';$('#recommendationReason').textContent=recommendationText(rec);
 const todays=state.logs.filter(x=>x.date===todayISO());const mins=todays.reduce((a,x)=>a+x.minutes,0),qs=todays.reduce((a,x)=>a+x.questions,0),cs=todays.reduce((a,x)=>a+x.correct,0);$('#todayMinutes').textContent=mins;$('#todayQuestions').textContent=qs;$('#todayAccuracy').textContent=qs?accuracy(qs,cs)+'%':'--';$('#dailyProgress').style.width=Math.min(100,mins/modeTarget()*100)+'%';
 const week=state.logs.filter(x=>isWithinDays(x.date,7));const wm=week.reduce((a,x)=>a+x.minutes,0),wq=week.reduce((a,x)=>a+x.questions,0);$('#weekHours').textContent=(wm/60).toFixed(1).replace('.',',')+'h';$('#weekQuestions').textContent=wq;$('#weekEssays').textContent=state.essays.filter(x=>isWithinDays(x.date,7)).length;
 const ranked=[...activeConfigs()].sort((a,b)=>recommendationScore(b)-recommendationScore(a)).slice(0,5);$('#upcomingBlocks').innerHTML=ranked.map((b,i)=>{const s=subjectStats(b),status=subjectStatus(b);return`<div class="cycle-item ${b.s===cur.s?'current':''}"><div class="n">${i+1}</div><div><strong>${b.s}</strong><span>${s.done}/${s.target} blocos · ${b.minutes} min</span></div><button class="status-pill ${status.cls} quick-subject" data-subject="${encodeURIComponent(b.s)}">${status.label}</button></div>`}).join('');$$('.quick-subject').forEach(b=>b.onclick=()=>openTopicPicker(decodeURIComponent(b.dataset.subject)));renderHomeReviews();updateTimerDisplay()}
function renderHomeReviews(){if(!state.settings.showReviewsHome){$('#homeReviews').innerHTML='<div class="empty">Lembretes ocultos nas configurações.</div>';return}const due=getReviews().filter(x=>x.due<=todayISO()).slice(0,4);$('#homeReviews').innerHTML=due.length?due.map(reviewHTML).join(''):'<div class="empty">Nenhuma revisão vencida. O quadro está respirando.</div>'}
function renderCycle(){const configs=state.cycleConfig,done=configs.filter(x=>x.enabled).reduce((n,x)=>n+Math.min(Number(state.cycleProgress[x.s]||0),Number(x.target)||1),0),target=configs.filter(x=>x.enabled).reduce((n,x)=>n+(Number(x.target)||1),0);$('#roundDone').textContent=done;$('#roundTarget').textContent=target;$('#roundPercent').textContent=(target?Math.round(done/target*100):0)+'%';$('#cycleList').innerHTML=configs.map((b,i)=>{const s=subjectStats(b),status=subjectStatus(b);return`<div class="cycle-config-item ${b.enabled?'':'disabled'}" data-subject="${encodeURIComponent(b.s)}"><label class="cycle-name"><input type="checkbox" class="cycle-enabled" ${b.enabled?'checked':''}><span><strong>${b.s}</strong><small>${b.c} · <span class="status-pill ${status.cls}">${status.label}</span></small><span class="cycle-progress-label"><span>${s.done}/${s.target} blocos</span><span>${Math.min(100,Math.round(s.done/s.target*100))}%</span></span><span class="progress"><span style="width:${Math.min(100,s.done/s.target*100)}%"></span></span></span></label><label class="field"><span>Blocos/rodada</span><input class="cycle-target" type="number" min="1" max="10" value="${b.target}"></label><label class="field"><span>Duração</span><select class="cycle-minutes">${[30,45,60,90].map(m=>`<option value="${m}" ${m===Number(b.minutes)?'selected':''}>${m} min</option>`).join('')}</select></label><div class="move-actions"><button class="move-up" aria-label="Mover ${b.s} para cima" ${i===0?'disabled':''}>↑</button><button class="move-down" aria-label="Mover ${b.s} para baixo" ${i===configs.length-1?'disabled':''}>↓</button><button class="start-subject" aria-label="Estudar ${b.s}">▶</button></div></div>`}).join('');bindCycleConfig()}
function bindCycleConfig(){$$('.cycle-config-item').forEach((row,i)=>{const subject=decodeURIComponent(row.dataset.subject),config=state.cycleConfig.find(x=>x.s===subject);row.querySelector('.cycle-enabled').onchange=e=>{config.enabled=e.target.checked;if(!activeConfigs().length){config.enabled=true;alert('Mantenha pelo menos uma matéria ativa.')}if(!state.cycleConfig.find(x=>x.s===state.selectedSubject)?.enabled){state.selectedSubject=activeConfigs()[0].s;state.selectedTopic='';state.selectedMinutes=activeConfigs()[0].minutes;resetTimer()}save();render()};row.querySelector('.cycle-target').onchange=e=>{config.target=Math.max(1,Math.min(10,Number(e.target.value)||1));save();render()};row.querySelector('.cycle-minutes').onchange=e=>{config.minutes=Number(e.target.value);if(state.selectedSubject===subject){state.selectedMinutes=config.minutes;resetTimer()}save();render()};row.querySelector('.move-up').onclick=()=>moveConfig(i,-1);row.querySelector('.move-down').onclick=()=>moveConfig(i,1);row.querySelector('.start-subject').onclick=()=>openTopicPicker(subject)})}
function moveConfig(index,delta){const next=index+delta;if(next<0||next>=state.cycleConfig.length)return;[state.cycleConfig[index],state.cycleConfig[next]]=[state.cycleConfig[next],state.cycleConfig[index]];save();renderCycle()}
function renderSyllabus(){
 const query=($('#syllabusSearch')?.value||'').trim().toLocaleLowerCase('pt-BR'),stats=syllabusStats();$('#syllabusProgress').textContent=stats.p+'%';$('#homeSyllabusProgress').textContent=stats.p+'%';
 const list=syllabus.map(x=>{const topics=x.t.filter(t=>!query||x.s.toLocaleLowerCase('pt-BR').includes(query)||t.toLocaleLowerCase('pt-BR').includes(query));if(!topics.length)return'';const complete=x.t.filter(t=>state.syllabusDone?.[topicKey(x.s,t)]).length;
  return `<details class="subject-details" ${query?'open':''}><summary><div><strong>${x.s}</strong><span>${x.q} questões · ${x.t.length} assuntos</span></div><b>${complete}/${x.t.length}</b></summary><div class="topic-list">${topics.map(t=>{const key=topicKey(x.s,t),done=!!state.syllabusDone?.[key];return`<label class="topic-check ${done?'done':''}"><input type="checkbox" class="topic-done" data-key="${encodeURIComponent(key)}" ${done?'checked':''}><span>${t}</span></label>`}).join('')}</div></details>`;
 }).join('');
 $('#syllabusList').innerHTML=list||'<div class="empty">Nenhum assunto encontrado.</div>';
 $$('.topic-done').forEach(input=>input.onchange=()=>{const key=decodeURIComponent(input.dataset.key);state.syllabusDone[key]=input.checked;save();renderSyllabus()});
}
function getReviews(){const fromLogs=state.logs.filter(x=>x.reviewDate).map(x=>({id:x.id,type:'log',subject:x.subject,topic:x.topic,due:x.reviewDate,detail:x.questions?`${x.correct}/${x.questions} (${accuracy(x.questions,x.correct)}%)`:'Revisão ativa'}));const errs=state.errors.filter(x=>!x.done).map(x=>({id:x.id,type:'error',subject:x.subject,topic:x.topic,due:x.due,detail:x.prompt}));return [...fromLogs,...errs].sort((a,b)=>a.due.localeCompare(b.due))}
function reviewHTML(x){return `<div class="review-item"><div class="row"><div><strong>${x.subject}: ${x.topic}</strong><div class="subtle">${x.detail}</div></div><div style="text-align:right"><span class="badge ${x.due<=todayISO()?'red':'gold'}">${formatDate(x.due)}</span><div class="actions" style="margin-top:7px;justify-content:flex-end"><button class="btn secondary review-result" data-id="${x.id}" data-type="${x.type}" data-days="2">Errei</button><button class="btn secondary review-result" data-id="${x.id}" data-type="${x.type}" data-days="7">Dúvida</button><button class="btn review-result" data-id="${x.id}" data-type="${x.type}" data-days="0">Dominei</button></div></div></div></div>`}
function renderReviews(){const list=getReviews();let html='';if(reviewTab==='due'){const due=list.filter(x=>x.due<=todayISO());html=due.length?due.map(reviewHTML).join(''):'<div class="empty">Nenhuma revisão vencida.</div>'}else if(reviewTab==='all'){html=list.length?list.map(reviewHTML).join(''):'<div class="empty">Nenhuma revisão registrada.</div>'}else{const errs=state.errors.filter(x=>!x.done);html=errs.length?errs.map(x=>`<div class="error-item"><div class="row"><div><strong>${x.subject}: ${x.topic}</strong><div class="subtle"><b>Erro:</b> ${x.mistake}</div><div class="subtle"><b>Regra:</b> ${x.rule}</div><div class="subtle"><b>Pergunta:</b> ${x.prompt}</div></div><button class="btn secondary error-done" data-id="${x.id}">Dominei</button></div></div>`).join(''):'<div class="empty">O caderno de erros está vazio.</div>'}$('#reviewContent').innerHTML=html;bindReviewButtons()}
function bindReviewButtons(){$$('.review-result').forEach(b=>b.onclick=()=>{const days=Number(b.dataset.days);if(b.dataset.type==='error'){const e=state.errors.find(x=>x.id===b.dataset.id);if(e){if(days===0)e.done=true;else e.due=cappedReviewDate(todayISO(),days,e.subject)}}else{const l=state.logs.find(x=>x.id===b.dataset.id);if(l)l.reviewDate=days===0?'':cappedReviewDate(todayISO(),days,l.subject)}save();render()});$$('.error-done').forEach(b=>b.onclick=()=>{const e=state.errors.find(x=>x.id===b.dataset.id);if(e)e.done=true;save();render()})}
function renderEssay(){const arr=[...state.essays].sort((a,b)=>b.date.localeCompare(a.date));$('#essayHistory').innerHTML=arr.length?arr.map(x=>{const total=x.arg+x.coh+x.morph+x.orth;return `<div class="essay-item"><div class="row"><div><strong>${x.type}: ${x.theme}</strong><div class="subtle">${formatDate(x.date)} · ${x.notes||'Sem observação'}</div></div><span class="score ${scoreClass(total/20*100)}">${total}/20</span></div></div>`}).join(''):'<div class="empty">Nenhum treino de redação registrado.</div>'}
function renderPerformance(){const mins=state.logs.reduce((a,x)=>a+x.minutes,0),qs=state.logs.reduce((a,x)=>a+x.questions,0),cs=state.logs.reduce((a,x)=>a+x.correct,0);$('#totalHours').textContent=(mins/60).toFixed(1).replace('.',',')+'h';$('#totalQuestions').textContent=qs;$('#overallAccuracy').textContent=qs?accuracy(qs,cs)+'%':'--';let chart='';subjects.forEach(s=>{const a=state.logs.filter(x=>x.subject===s),q=a.reduce((z,x)=>z+x.questions,0),c=a.reduce((z,x)=>z+x.correct,0),p=accuracy(q,c);if(q)chart+=`<div class="bar-row"><span>${s.replace('Direito ','Dir. ').replace('Raciocínio Lógico-Matemático','RLM').replace('Legislação Específica','Legislação')}</span><div class="bar"><span style="width:${p}%"></span></div><b>${p}%</b></div>`});$('#subjectChart').innerHTML=chart||'<div class="empty">Registre questões para gerar o gráfico.</div>';
 const sims=[...state.sims].sort((a,b)=>b.date.localeCompare(a.date));$('#simHistory').innerHTML=sims.length?sims.map(x=>`<div class="sim-item"><div class="row"><div><strong>${x.exam} · ${formatDate(x.date)}</strong><div class="subtle">${x.minutes} min · ${x.notes||'Sem gargalo registrado'}</div></div><span class="score ${scoreClass(accuracy(x.questions,x.correct))}">${x.correct}/${x.questions} (${accuracy(x.questions,x.correct)}%)</span></div></div>`).join(''):'<div class="empty">Nenhum simulado registrado.</div>';
 const logs=[...state.logs].sort((a,b)=>(b.date+b.created).localeCompare(a.date+a.created)).slice(0,15);$('#studyHistory').innerHTML=logs.length?logs.map(x=>`<div class="log-item"><div class="row"><div><strong>${x.subject}: ${x.topic}</strong><div class="subtle">${formatDate(x.date)} · ${x.minutes} min · ${x.method}</div></div><span class="score ${scoreClass(accuracy(x.questions,x.correct))}">${x.questions?accuracy(x.questions,x.correct)+'%':'—'}</span></div></div>`).join(''):'<div class="empty">Nenhum estudo registrado.</div>'}
function renderSettings(){const s=state.settings;$('#examDate').value=s.examDate;$('#soldierExamDate').value=s.soldierExamDate||'';$('#weeklyHoursGoal').value=s.weeklyHoursGoal;$('#weeklyQuestionGoal').value=s.weeklyQuestionGoal;$('#showReviewsHome').checked=s.showReviewsHome}
function updateTimerDisplay(){const m=Math.floor(timerSeconds/60).toString().padStart(2,'0'),s=(timerSeconds%60).toString().padStart(2,'0');$('#timerDisplay').textContent=`${m}:${s}`;const total=Math.max(60,state.selectedMinutes*60);$('#timerProgress').style.width=((total-timerSeconds)/total*100)+'%';$('#timerStart').textContent=timerRunning?'Pausar':'Iniciar bloco'}
function toggleTimer(){if(timerRunning){clearInterval(timerId);timerRunning=false}else{timerRunning=true;timerId=setInterval(()=>{timerSeconds--;if(timerSeconds<=0){clearInterval(timerId);timerRunning=false;timerSeconds=0;navigator.vibrate?.([200,100,200]);alert('Bloco concluído. Registre o estudo e escolha o próximo passo.')}updateTimerDisplay()},1000)}updateTimerDisplay()}
function resetTimer(){clearInterval(timerId);timerRunning=false;timerSeconds=state.selectedMinutes*60;updateTimerDisplay()}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
function openSubjectPicker(){const query=($('#subjectSearch')?.value||'').trim().toLocaleLowerCase('pt-BR'),rec=recommendedConfig();$('#subjectPicker').innerHTML=activeConfigs().filter(x=>x.s.toLocaleLowerCase('pt-BR').includes(query)).map(config=>{const s=subjectStats(config),status=subjectStatus(config);return`<button class="subject-choice ${config.s===rec.s?'recommended':''}" data-pick="${encodeURIComponent(config.s)}"><span><strong>${config.s}${config.s===rec.s?' · recomendada':''}</strong><small>${s.done}/${s.target} blocos · ${config.minutes} min · ${config.g}</small></span><span class="status-pill ${status.cls}">${status.label}</span></button>`}).join('')||'<div class="empty">Nenhuma matéria ativa encontrada.</div>';$$('[data-pick]').forEach(b=>b.onclick=()=>{openTopicPicker(decodeURIComponent(b.dataset.pick));$('#subjectDialog').close()});if(!$('#subjectDialog').open)$('#subjectDialog').showModal()}
function openTopicPicker(subject){const config=state.cycleConfig.find(x=>x.s===subject);if(!config||!config.enabled)return;pendingSubject=subject;$('#topicSubject').value=subject;$('#topicSelect').innerHTML=subjectTopics(subject).map(t=>`<option value="${t}">${t}</option>`).join('');if(state.selectedSubject===subject&&state.selectedTopic&&subjectTopics(subject).includes(state.selectedTopic))$('#topicSelect').value=state.selectedTopic;$('#topicMinutes').value=String(config.minutes);$('#topicMethod').value=subject==='Redação Discursiva'?'Redação':subject==='Legislação Específica'?'Lei seca':'Questões por assunto';$('#topicDialog').showModal()}
function selectRecommended(){openTopicPicker(recommendedConfig().s)}
$$('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$$('.mode-btn').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;save();render()});$('#timerStart').onclick=toggleTimer;$('#timerReset').onclick=resetTimer;
$('#studyRecommended').onclick=selectRecommended;$('#chooseSubject').onclick=()=>{if(!$('#subjectDialog').open)openSubjectPicker()};$('#continueSubject').onclick=()=>openTopicPicker(current().s);$('#subjectSearch').addEventListener('input',openSubjectPicker);
$('#topicForm').onsubmit=e=>{e.preventDefault();state.selectedSubject=pendingSubject;state.selectedTopic=$('#topicSelect').value;state.selectedMinutes=Number($('#topicMinutes').value);save();resetTimer();render();$('#topicDialog').close();switchView('home');if($('#topicMethod').value)$('#studyMethod').value=$('#topicMethod').value};
$('#completeBlock').onclick=()=>{const cur=current(),topics=subjectTopics(cur.s);$('#studySubject').value=cur.s;$('#studyTopicOptions').innerHTML=topics.map(t=>`<option value="${t}"></option>`).join('');$('#studyDate').value=todayISO();$('#studyMinutes').value=state.selectedMinutes;$('#studyTopic').value=state.selectedTopic||'';$('#studyQuestions').value=0;$('#studyCorrect').value=0;$('#studyNotes').value='';$('#createErrorFromStudy').checked=false;$('#studyReviewDate').value=addDays(todayISO(),7);$('#studyDialog').showModal()};
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#studyQuestions').addEventListener('input',()=>{const q=Number($('#studyQuestions').value||0),c=Number($('#studyCorrect').value||0),p=accuracy(q,c),subject=$('#studySubject').value;$('#studyReviewDate').value=cappedReviewDate($('#studyDate').value||todayISO(),reviewInterval(p),subject)});
$('#studyCorrect').addEventListener('input',()=>$('#studyQuestions').dispatchEvent(new Event('input')));
$('#studyForm').onsubmit=e=>{e.preventDefault();const q=Number($('#studyQuestions').value),c=Math.min(q,Number($('#studyCorrect').value));const log={id:crypto.randomUUID(),created:new Date().toISOString(),date:$('#studyDate').value,subject:$('#studySubject').value,topic:$('#studyTopic').value,minutes:Number($('#studyMinutes').value),method:$('#studyMethod').value,questions:q,correct:c,energy:$('#studyEnergy').value,reviewDate:$('#studyReviewDate').value,notes:$('#studyNotes').value};state.logs.push(log);state.cycleProgress[log.subject]=Number(state.cycleProgress[log.subject]||0)+1;if($('#createErrorFromStudy').checked&&log.notes.trim()){state.errors.push({id:crypto.randomUUID(),subject:log.subject,topic:log.topic,due:log.reviewDate||addDays(log.date,2),mistake:log.notes,rule:'Revisar a explicação correta da questão.',prompt:`Qual foi a regra que corrige o erro em ${log.topic}?`,done:false})}save();$('#studyDialog').close();resetTimer();render();$('#postStudyDialog').showModal()};
$('#addErrorBtn').onclick=()=>{$('#errorSubject').innerHTML=subjects.map(s=>`<option>${s}</option>`).join('');$('#errorDue').value=addDays(todayISO(),2);$('#errorDialog').showModal()};
$('#errorForm').onsubmit=e=>{e.preventDefault();state.errors.push({id:crypto.randomUUID(),subject:$('#errorSubject').value,topic:$('#errorTopic').value,due:$('#errorDue').value,mistake:$('#errorMistake').value,rule:$('#errorRule').value,prompt:$('#errorPrompt').value,done:false});save();$('#errorDialog').close();e.target.reset();render()};
$$('[data-review-tab]').forEach(b=>b.onclick=()=>{reviewTab=b.dataset.reviewTab;$$('[data-review-tab]').forEach(x=>x.classList.toggle('active',x===b));renderReviews()});
$('#syllabusSearch').addEventListener('input',renderSyllabus);
$('#expandSyllabus').onclick=()=>{const items=$$('.subject-details'),openAll=items.some(x=>!x.open);items.forEach(x=>x.open=openAll);$('#expandSyllabus').textContent=openAll?'Recolher':'Expandir'};
$('#addEssayBtn').onclick=()=>{$('#essayDate').value=todayISO();$('#essayDialog').showModal()};
$('#essayForm').onsubmit=e=>{e.preventDefault();state.essays.push({id:crypto.randomUUID(),date:$('#essayDate').value,type:$('#essayType').value,theme:$('#essayTheme').value,arg:Number($('#essayArg').value),coh:Number($('#essayCoh').value),morph:Number($('#essayMorph').value),orth:Number($('#essayOrth').value),notes:$('#essayNotes').value});save();$('#essayDialog').close();e.target.reset();render()};
$('#addSimBtn').onclick=()=>{$('#simDate').value=todayISO();$('#simDialog').showModal()};
$('#simForm').onsubmit=e=>{e.preventDefault();state.sims.push({id:crypto.randomUUID(),date:$('#simDate').value,exam:$('#simExam').value,questions:Number($('#simQuestions').value),correct:Number($('#simCorrect').value),minutes:Number($('#simMinutes').value),timeIssue:$('#simTimeIssue').value,notes:$('#simNotes').value});save();$('#simDialog').close();e.target.reset();render()};
$('#postContinue').onclick=()=>{$('#postStudyDialog').close();openTopicPicker(current().s)};$('#postChoose').onclick=()=>{$('#postStudyDialog').close();openSubjectPicker()};$('#postRecommend').onclick=()=>{$('#postStudyDialog').close();selectRecommended()};
$('#resetCycle').onclick=()=>{if(confirm('Iniciar uma nova rodada e zerar apenas o progresso dos blocos? Seus registros continuarão salvos.')){state.cycleProgress={};state.roundNumber=Number(state.roundNumber||1)+1;save();render()}};
$('#restoreCycle').onclick=()=>{if(confirm('Restaurar matérias, metas, tempos e ordem recomendados? Seus registros continuarão salvos.')){state.cycleConfig=structuredClone(defaultCycle);state.selectedSubject='Língua Portuguesa';state.selectedTopic='';state.selectedMinutes=60;save();resetTimer();render()}};
$('#saveSettings').onclick=()=>{state.settings={...state.settings,examDate:$('#examDate').value,soldierExamDate:$('#soldierExamDate').value,weeklyHoursGoal:Number($('#weeklyHoursGoal').value),weeklyQuestionGoal:Number($('#weeklyQuestionGoal').value),showReviewsHome:$('#showReviewsHome').checked};save();render();alert('Configurações salvas.')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qg_cbm_rr_backup_'+todayISO()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=deepMerge(structuredClone(defaults),JSON.parse(r.result));save();resetTimer();render();alert('Backup importado.')}catch{alert('Arquivo inválido.')}};r.readAsText(f)};
$('#clearData').onclick=()=>{if(confirm('Apagar todos os registros? Esta ação não pode ser desfeita.')){state=structuredClone(defaults);save();resetTimer();render()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').style.display='block'});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').style.display='none'};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
render();